config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#splash"
  #user routes
  resources :users
#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PATCH  /users/:id(.:format)      users#update
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy

  get "/login", to: "sessions#new"

  post "/sessions", to: "sessions#create"

  get "/sign_up", to: "users#new", as: "sign_up"

  get "/logout",  to:  "sessions#destroy", as: "logout"

  #view page
  get "/views", to: "welcome#views", as: "views"

  get "/items", to: "items#new", as: "create_items"

  post "/items", to: "items#create"

 
  get "/items/:id", to: "items#show", as: "single_item"

  get "/search", to: "items#search", as: "search_items"

  get "/users/:id/items", to: "users#userItems", as: "user_items"

  patch "/users/:id/items", to: "items#updateItems", as: "update_items"

  get "/categories/:id/items", to: "items#index", as: "display_cat"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
	has_many :items, through: :category_items
	has_many :category_items
end

app/models/category_item.rb
class CategoryItem < ActiveRecord::Base
	belongs_to :category
	belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	geocoded_by :item_location  # can also be an IP address
	after_validation :geocode 

	def self.search(search)
		where("title LIKE ?", "%#{search}%") 
	end

	# def self.searchLocation(location)
		
	#     where("item_location LIKE ?", "%#{location}%") 
	# end


	# def self.searchLocationAndItem(search, location)
	# 	where("title LIKE ?", "%#{search}%","item_location LIKE ?", "%#{location}%")
	  	
	# end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_confirmation_of :password
	validates :email, :password, presence: true
	validates :email, uniqueness: true
	has_many :items
	geocoded_by :location  # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	

	def self.confirm(params)
	    @user = User.find_by({email: params[:email]})
	    @user.try(:authenticate, params[:password])
  	end
end

app/models/user_item.rb
class UserItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@category =Category.all
		@items= Category.find(params[:id]).items
		# binding.pry
	end

	def new
		@user = User.find(session[:user_id])
		@item = Item.new
		render :new
	end

	def create
		# TODO: add :image

		item_params = params.require(:item).permit(:title, :user_id, :price, :description, :condition, :image, :item_location, :category_id)
	    @item = Item.create(item_params)
	    Category.find(item_params[:category_id]).items << @item
	    redirect_to views_path
	end

	

	def show
		item_id = params[:id]
		@item = Item.find(item_id)

		@users = User.all
		@hash = Gmaps4rails.build_markers(@item) do |item, marker|
  			marker.lat item.latitude
  			marker.lng item.longitude
  		end
	end

	def updateItems
    	user_id = params[:id]
    	@user= User.find(user_id)
		updateditems = params.require(:item).permit(:title, :price, :description, :condition, :item_location, :image)
		
		@item = @user.items.update(updateItems)
		redirect_to "/users/#{user_id}/items"
	end

	def search
		@category = Category.all

      if params[:search] != "" && params[:location] != "" 
      	@items = Item.where(:title => params[:search].strip, :item_location => params[:location].strip)

      elsif params[:search] != "" 
      	@items= Item.where(:title =>params[:search].strip)

	  elsif params[:location] != ""
      	
		  @items = Item.where(:item_location => params[:location].strip)
		else
			redirect_to :back
	    end

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
    @user = User.new
	end

  def create
  	user_params = params.require(:user).permit( :email, :password)
  	@user = User.confirm(user_params)
		if @user
  			login(@user)
  			redirect_to views_path
		else
  			redirect_to root_path
		end
	end

	def destroy
		@current_user = session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :location)
	    @user = User.create(user_params)
	    login(@user)
	    redirect_to views_path
	end

	def show
    	@user = User.find(params[:id])
	end

	def update
		# binding.pry
        user_id = params[:id]
        @user = User.find(user_id)

        # get updated data
        updated_attributes = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        # update the creature
        @user.update(updated_attributes)

        #redirect to show
        redirect_to "/users/#{user_id}"
    end

    def userItems
    	if params[:id].to_i == session[:user_id].to_i
    		@user = User.find(params[:id])
	    	render :useritems
	    else
	    	redirect_to user_path(params[:id])
	    end

    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def splash
		@user =User.new
	end
	
	def views
		@category = Category.all
		@item = Item.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logged_in?
    if current_user == nil
      redirect_to root_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.erb
<h1 class="transbox search-font"> Search Items</h1>
  <%= form_tag(search_items_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append form-group">
      <!-- add `remote: true` option for async -->
      <%= text_field_tag :search, params[:search], placeholder: "Search items", class: "form-control" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
       <%= text_field_tag :location, params[:location], placeholder: "Enter Location", class: "form-control" %>    
      <%= submit_tag "Search", class: "btn btn-default" %>
    </div>
  <% end %>


 <div class="container-fluid col-md-2 panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Browse Categories</h4>
    </div>
      <div class="panel-body">
        <ul class='list-unstyled'>
          <% @category.each do |category| %>
            <li> <a href="/categories/<%= category.id %>/items"> <%= category.name %> </a> </li>
          <% end %>
        </ul>
      </div>
</div>
    <div>
      <h2> Browse Items</h2>

      
      <div class="col-md-10">
        <% @items.each do |item| %>

          <div class='col-md-3'>
            <div id="item-img">
          <img class="img-show"src="<%= item.image %>">
          </div>
          <a data-no-turbolink="true" href="/items/<%= item.id %>"> <%= item.title %> </a><br>
          
          <%= item.price %><br>
          <%= item.condition %><br>
          <%= item.description %><br>
          <%= item.item_location %><br>
          </div>
        <% end %>
      </div>
</div>

app/views/items/new.html.erb
<%= form_for [@item] do |f| %>
        <div>
          <%= f.text_field :title, placeholder: "name your item", class: 'form-control' %>

        </div> <br>
        <div>
          <%= f.text_field :price, placeholder: "Enter amount", class: 'form-control' %>
        </div><br>
        <div>
          <%= f.text_field :description, placeholder: "description of the item", class: 'form-control' %>
        </div><br>
        <div>
          <%= f.select :category_id, 
             [["Electronics",1], ["Antiques",2], ["Appliances",3], ["Arts & Crafts",4], ["Audio Equipment",5], ["Auto parts",6], ["Tickets",7], ["Video Games",8], ["Sports & Outdoors",9],
              ["Baby & kids",10], ["Beauty & Health",11], ["Bicycles",12], ["Books & Magazines",13], ["Furniture",14], ["Motorcycles",15],["Musical Instruments",16], ["Photography",17], ["TV's",18],
              ["Motorcycles",19], ["Jewelry",20], ["services",21], ["Cell Phones",22], ["Clothing",23], ["Collectibles",24], ["Boats & Marine",25], ["Cars & Trucks",26]], class: 'form-control' %>

        
        </div><br>
        <div>
          <%= f.text_field :condition, placeholder: "condition", class: 'form-control' %>
        </div><br>
        <div>
          <%= f.text_field :item_location, :value => @user.location, class: 'form-control'%>
          <%= f.hidden_field(:user_id, :value => @user.id)%>
        </div><br>
        <div>
          <input type="hidden" role="uploadcare-uploader" name="item[image]"
          data-crop="disabled"
          data-preview-step="true"
          data-images-only="true" />
        </div><br>
        <%= f.submit "Post item" %>
        <% end %> 

app/views/items/search.html.erb
<h1 class="transbox search-font"> Search Items</h1>
  <%= form_tag(search_items_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append form-group">
      <!-- add `remote: true` option for async -->
      <%= text_field_tag :search, params[:search], placeholder: "Search items", class: "form-control" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
       <%= text_field_tag :location, params[:location], placeholder: "Enter Location", class: "form-control" %>    
      <%= submit_tag "Search", class: "btn btn-default" %>
    </div>
  <% end %>


<div class="container-fluid col-md-2 panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Browse Categories</h4>
    </div>
      <div class="panel-body">
        <ul class='list-unstyled'>
          <% @category.each do |category| %>
            <li> <a href="/categories/<%= category.id %>/items"> <%= category.name %> </a> </li>
          <% end %>
        </ul>
      </div>
</div>
        
        <% if @items.present? %>
       <h2> Items located near: <%=@items[0].item_location %></h2>
            <% else %>
          <p>There are no <%= params[:search] %> listed in <%= params[:location] %>.</p>
          <p>Search items in another nearest location.</p>
      <% end %>




      
      <div class="col-md-10">
        <% @items.each do |item| %>

          <div class='col-md-3'>
            <div id="item-img">
          <img class="img-show"src="<%= item.image %>">
          </div>
          <a data-no-turbolink="true" href="/items/<%= item.id %>"> <%= item.title %> </a><br>
          
          <%= item.price %><br>
          <%= item.condition %><br>
          <%= item.description %><br>
          <%= item.item_location %><br>
          </div>
        <% end %>
      </div>
</div>

app/views/items/show.html.erb
<h3><%= @item.title %></h3>
<div id="item-img">
<img class="img-show" src="<%= @item.image %>">
</div>
<h3>Asking Price: <%= @item.price %></h3>
<h3>Condition: <%= @item.condition %></h3>
<h3>Description: <%= @item.description %></h3>
<h3>Located at: <%= @item.item_location %></h3>

   
<button data-toggle="modal" data-target="#messageModal" style="display: inline" class="btn btn-primary">
 Ask Seller
</button>
<%= link_to "Browse all items", views_path %>
        
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow:visible">
	<div class="modal-dialog" role="document">
	    <div class="modal-content motra">
	        <div class="modal-header">
	        	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
	        	</button>
	        		<h4 class="modal-title text" id="myModalLabel">Send message</h4>
	      	</div>
	      		<div class="modal-body">
	      
					<%= form_tag do |f| %>
			    	
			 		<%= text_area_tag(:message, "Hi, nice site", size: "24x6") %>
			   
					<% end %> 
				</div>
	  	</div>
	</div>
</div> 
               
<!-- modal ends -->
   
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type="text/javascript">
      handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dealup</title>
  <script>
     UPLOADCARE_LOCALE = "en";
     UPLOADCARE_TABS = "file url facebook gdrive dropbox instagram evernote flickr skydrive";
     UPLOADCARE_PUBLIC_KEY = "4b8804e6c4cfb1665d43";
   </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHLett8djBo62dDXj0EjCimF8Rd6E8cxg"></script> -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places,geometry"></script>
  <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
  <script charset="utf-8" src="https://ucarecdn.com/widget/2.5.5/uploadcare/uploadcare.full.min.js"></script> 
</head>
<body>
  <div class="wrapper">
      <%= render 'partials/navbar' %>
      <div class="container">
      		<%= yield %>
      </div>
        <div class="push"></div>
  </div>

      <%=render 'partials/footer' %>

</body>
</html>

app/views/partials/_footer.html.erb
<div class="footer">
        <ul class="menu-social">
            <li>
                <a href="https://twitter.com"><i class="fa fa-twitter"></i>
                </a>
            </li> 
            <li>
                <a href="https://facebook.com"><i class="fa fa-facebook"></i>
                </a>
            </li> 
            <li>
                <a href="https://instagram.com"><i class="fa fa-instagram"></i>
                </a>
            </li> 
            <li>
                <a href="https://plus.google.com"><i class="fa fa-google-plus"></i>
                </a>
            </li> 
            <li>
                <a href="https://pinterest.com"><i class="fa fa-pinterest"></i>
                </a>
            </li> 
        </ul> 
        <div class="size-small">© 2015 Dealnow, Inc.</div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse pos-relative green" id ="navBar">
  <div class="container">
    	<div class="navbar-header">
        	<a class="navbar-brand" href="/views"><span id="navtext">Make-a-Deal</span></a> 
      </div>
      <div id="profile-dashboard">
          <% if current_user %>
          <% @user = @current_user %>
      <div class="media-right pull-right">
            <h4 style="display: inline"> Welcome <%= link_to @user.first_name, user_path(@user.id), :style => "color: white;" %> </h4>
                <div class="button-group" role="group" style="display: inline">
                   <%= button_to "Logout", logout_path, method: "get", class: "red navbar-btn btn btn-danger" %>
                </div>
      </div>
  </div>
        <% else %>
        <div id="init-user-btns">
               <button data-toggle="modal" data-target="#loginModal" style="display: inline"
                   class="btn btn-primary navbar-right navbar-btn">
                 Log In
               </button>
               <button data-toggle="modal" data-target="#signUpModal" style="display: inline" class="btn btn-primary navbar-right navbar-btn">
                 Sign Up
               </button>
        </div>
        <% end %>
  </div>
</nav>

app/views/users/show.html.erb
<%= link_to "Browse all items", views_path %>
<p> firstname : <%= @user.first_name %> </p>
<p> lastname : <%= @user.last_name %> </p>
<p> email address : <%= @user.email %> </p>
<p> member since : <%= @user.created_at %> </p>
<button type="button" data-toggle="modal" data-target="#update">update profile </button><br><br>
<button><%= link_to "sell your items here", create_items_path %></button>
<button><%= link_to "see your items here", user_items_path(@user.id) %></button>


<div class="modal fade" id="update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow:visible">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content motra">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title text" id="myModalLabel">Update Info</h4>
	      </div>
	      <div class="modal-body">
	      
			<%= form_for @user do |f| %>
			    <div class="form-group">
			     <span> <%= f.text_field :first_name, placeholder: "First name", class: 'form-control' %></span>
			    </div> <br>
			    <div class="form-group">
			     <span> <%= f.text_field :last_name, placeholder: "Last name", class: 'form-control' %></span>
			    </div> <br>
			    
			    <div class="form-group">
			      <%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
			    </div><br>
			    <div class="form-group">
			      <%= f.password_field :password, placeholder: "New Password", class: 'form-control' %>
			    </div><br>
			    <div class="form-group">
			      <%= f.password_field :password_confirmation, placeholder: "Confirm New Password", class: 'form-control' %>
			    </div><br>
			    <%= f.submit "Update", class: 'btn btn-primary' %>
			<% end %> 
		</div>

				<div class="modal-footer">
					<span class="text">
            		Already have an account
            		</span>
            		<button data-toggle="modal" data-target="#loginModal" data-dismiss="modal" style="display: inline" class="btn btn-default success">
                 	click Here
               		</button>
        		</div>

	    </div>
	  </div>
	</div>
	</div>

app/views/users/useritems.html.erb
<% @user.items.each do |item| %>
	<div id="item-img">
          <img class="img-show"src="<%= item.image %>">
    </div>
    title:<%= item.title %><br>
    Description: <%= item.description %><br>
    Location:<%= item.item_location %><br>
    <button type="button" data-toggle="modal" data-target="#updateitem">update item</button>



<!-- Modal begins -->
<div class="modal fade" id="updateitem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow:visible">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      	<div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title text" id="myModalLabel">Update Info</h4>
	      	</div>
	      	<div class="modal-body">
	      
				<%= form_for item, url: update_items_path, html: { method: :patch } do |f| %>
				    <div class="form-group">
				     <span> <%= f.text_field :title, placeholder: "Enter name", class: 'form-control' %></span>
				    </div> <br>
				    <div class="form-group">
				     <span> <%= f.text_field :price, placeholder: "Enter new amount", class: 'form-control' %></span>
				    </div> <br>
				    
				    <div class="form-group">
				      <%= f.text_field :description, placeholder: "Enter description", class: 'form-control' %>
				    </div><br>
				    
				    <div class="form-group">
				      <%= f.text_field :condition, placeholder: "what is your item condition?", class: 'form-control' %>
				    </div><br>
				    <%= f.submit "Update", class: 'btn btn-primary' %>
				<% end %> 
			</div>
		</div>
	  </div>
	</div>
</div>

<% end %>

app/views/welcome/splash.html.erb
<div class="welcome">
	<!-- signUpModal -->
	
	<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow:visible">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content motra">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title text" id="myModalLabel">Create an account</h4>
	      </div>
	      <div class="modal-body">
	      
			<%= form_for @user do |f| %>
			    <div class="form-group">
			     <span> <%= f.text_field :first_name, placeholder: "First name", class: 'form-control' %></span>
			    </div> <br>
			    <div class="form-group">
			     <span> <%= f.text_field :last_name, placeholder: "Last name", class: 'form-control' %></span>
			    </div> <br>
			    
			    <div class="form-group">
			      <%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
			    </div><br>
			    <div class="form-group">
			      <%= f.password_field :password, placeholder: "Password", class: 'form-control' %>
			    </div><br>
			    <div class="form-group">
			      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control' %>
			      <%=f.text_field :location, placeholder: "Enter location", class: 'form-control' %>
			    </div><br>
			    <%= f.submit "Sign Up", class: 'btn btn-primary' %>
			<% end %> 
		</div>

				<div class="modal-footer">
					<span class="text">
            		Already have an account
            		</span>
            		<button data-toggle="modal" data-target="#loginModal" data-dismiss="modal" style="display: inline" class="btn btn-default success">
                 	click Here
               		</button>
        		</div>

	    </div>
	  </div>
	</div>
	</div>

	<!-- Login Modal -->
	<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow:visible">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content motra">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title text" id="myModalLabel">Login</h4>
	      </div>
		      <div class="modal-body">
		      
				<%= form_for @user, url: sessions_path do |f| %>
				    <div>
				      <%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
				    </div><br>
				    <div>
				      <%= f.password_field :password, placeholder: "Password" , class: 'form-control'%>
				    </div><br>
				    <%= f.submit "Login" , class: 'btn btn-primary'%>
				<% end %> 
			  </div>
			<div class="modal-footer">
				<span class="text">
            New to Make-a-Deal?
            	</span>
            <button data-toggle="modal" data-target="#signUpModal" data-dismiss="modal" style="display: inline" class="btn btn-sm btn-default success">
                Register Here
               </button>
            
        	</div>	

	    </div>
	  </div>
	</div>
</div>

app/views/welcome/views.html.erb
<h1 class="transbox search-font"> Search Items</h1>
  <%= form_tag(search_items_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append form-group">
      <!-- add `remote: true` option for async -->
      <%= text_field_tag :search, params[:search], placeholder: "Search items", class: "form-control" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
       <%= text_field_tag :location, params[:location], placeholder: "Enter Location", class: "form-control" %>    
      <%= submit_tag "Search", class: "btn btn-default" %>
    </div>
  <% end %>


<div class="container-fluid col-md-2 panel panel-default cat">
    <div class="panel-heading">
        <h4 class="panel-title">Browse Categories</h4>
    </div>
      <div class="panel-body">
        <ul class='list-unstyled'>
        	<% @category.each do |category| %>
            <li> <a href="/categories/<%= category.id %>/items"> <%= category.name %> </a> </li>
          <% end %>
        </ul>
      </div>
</div>


<div class="cat">
  <div class="panel-panel-default">
    <h2> Browse Items</h2>
  </div>

  
  <div>
    <% @item.each do |item| %>

      <div class='col-md-3 box'>
            <div id="item-img">
                <img class="img-show"src="<%= item.image %>">
            </div>
          <a data-no-turbolink="true" href="/items/<%= item.id %>"> <%= item.title %> </a><br>
          
          <p>Price: $<%= item.price %></p>
          <p>condition: <%= item.condition %></p>
          <p>description: <%= item.description %></p>
          <p>Located at: <%= item.item_location %></p>
      </div>
    <% end %>
</div>
</div>